name: Firebase Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: npm install -g firebase-tools
      - name: Login to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: firebase login:ci --no-localhost --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: firebase deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
